# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
users = [{:nombre => 'Rubén Aguirre Jirafales',:email => 'profjirafales@elchavo.com',:password => "clave12345", :password_confirmation => "clave12345", :tipo => '2', :habilitado => 'true'},
         {:nombre => 'Sr. Pepito Argento',:email => 'admin@club.com', :password => "clave12345", :password_confirmation => "clave12345", :tipo => '1', :habilitado => 'true'}
     ]

users.each do |user|
   User.create!(user)
end

groups = [{:nombre => 'group0 v',:sexo => '1',:quota => '10', :extended_quota => '1', :initial_age => '3', :maximun_age => '4'},
          {:nombre => 'group1 m',:sexo => '2',:quota => '10', :extended_quota => '1', :initial_age => '5', :maximun_age => '6'},
          {:nombre => 'group3 mix',:sexo => '3',:quota => '10', :extended_quota => '1', :initial_age => '7', :maximun_age => '8'},
          {:nombre => 'group4 v',:sexo => '1',:quota => '10', :extended_quota => '1', :initial_age => '9', :maximun_age => '10'},
          {:nombre => 'group5 m',:sexo => '2', :quota => '10', :extended_quota => '1', :initial_age => '11', :maximun_age => '12'}
     ]

groups.each do |group|
   Group.create!(group)
end

colonists = [
   {:colonist_name => 'Juan Román Riquelme',
    :colonist_age => '10',
    :colonist_birtday => '11/04/2005',
    :colonist_gender => '1',
    :colonist_dni => '37455687',
    :colonist_address => 'Laprida 2376 Piso 1 Depto 3',
    :colonist_telephone => '123123123',
    :colonist_email => '1pepe@yahoo.com',
    :colonist_school_name => 'Saint Patric',
    :colonist_grade => '5',
    :colonist_school_address => 'Humboldt 5543',
    :colonist_school_phone => '1147852365',
    :colonist_medical_insurance => 'Osde',
    :colonist_trauma => 'no',
    :colonist_surgery => 'no',
    :colonist_illness_asthma => 'false',
    :colonist_illness_allergy => 'no',
    :colonist_illness_heart_failure => 'false',
    :colonist_illness_diabetes => 'false',
    :colonist_illness_other => 'no',
    :colonist_medical_observation => 'false',
    :colonist_doctor => 'true',
    :colonist_know_swim => 'true',
    :colonist_swim_school => 'ninguna',
    :colonist_swim_leave_reasons => 'no se',
    :how_know_us => 'Vi publicidad en facebook',
    :parents_relation => 'Casados',
    :father_name => 'Augusto Riquelme',
    :father_age => '43',
    :father_lives => 'true',
    :father_visit => 'true',
    :father_email => 'ariquelme@mail.com',
    :father_profession => 'deportista',
    :father_work_phone => '11 1574598632',
    :mother_name => 'Gregoria Matorras',
    :mother_age => '37',
    :mother_lives => 'true',
    :mother_visit => 'true',
    :mother_email => 'momimail@correo.com',
    :mother_profession => 'ama de casa',
    :mother_work_phone => '11 478563256',
    :who_register => 'Madre',
    :i_attest => 'true',
    :group_id => '4'
  },
  { :colonist_name => 'Sebastián Pascual Rambert',
    :colonist_age => '9',
    :colonist_birtday => '1/07/2006',
    :colonist_gender => '1',
    :colonist_dni => '38412871',
    :colonist_address => 'Av Robertsons 5343 Piso 1 Depto 3',
    :colonist_telephone => '123123123',
    :colonist_email => '2pepe@yahoo.com',
    :colonist_school_name => 'Esclavas del sagrado corazón de jesus',
    :colonist_grade => '4',
    :colonist_school_address => 'Darragueira Nº 2375',
    :colonist_school_phone => '11473364427',
    :colonist_medical_insurance => 'Osecac',
    :colonist_trauma => 'no',
    :colonist_surgery => 'si, extracción de apéndica',
    :colonist_illness_asthma => 'false',
    :colonist_illness_allergy => 'polen de lavanda',
    :colonist_illness_heart_failure => 'false',
    :colonist_illness_diabetes => 'false',
    :colonist_illness_other => 'no',
    :colonist_medical_observation => 'true',
    :colonist_doctor => 'true',
    :colonist_know_swim => 'true',
    :colonist_swim_school => 'ninguna',
    :colonist_swim_leave_reasons => 'no se',
    :how_know_us => 'Vi publicidad buscando en google',
    :parents_relation => 'Casados',
    :father_name => 'Alberto Rambert',
    :father_age => '40',
    :father_lives => 'true',
    :father_visit => 'true',
    :father_email => 'arambert@mail.com',
    :father_profession => 'Desarrollador de software',
    :father_work_phone => '11 1754632872',
    :mother_name => 'Remedios Escalada',
    :mother_age => '39',
    :mother_lives => 'true',
    :mother_visit => 'true',
    :mother_email => 'reme_dios@correo.com',
    :mother_profession => 'Administradora de empresas',
    :mother_work_phone => '11 745123697',
    :who_register => 'Madre',
    :i_attest => true,
    :group_id => '4'
  },
  { :colonist_name => 'Josemir Lujambio',
    :colonist_age => '9',
    :colonist_birtday => '9/03/2006',
    :colonist_gender => '1',
    :colonist_dni => '38475325',
    :colonist_address => 'Avenida de las camelias 3741 Piso 8 Depto 3',
    :colonist_telephone => '123123123',
    :colonist_email => '3pepe@yahoo.com',
    :colonist_school_name => 'Escuela primaria Sargento Cabral',
    :colonist_grade => '4',
    :colonist_school_address => 'Benjamín Matienzo Nº 7535',
    :colonist_school_phone => '11446287643',
    :colonist_medical_insurance => 'Swiss Medical Group',
    :colonist_trauma => 'no',
    :colonist_surgery => 'si, extracción de vesícula biliar',
    :colonist_illness_asthma => 'false',
    :colonist_illness_allergy => 'no',
    :colonist_illness_heart_failure => 'false',
    :colonist_illness_diabetes => 'false',
    :colonist_illness_other => 'no',
    :colonist_medical_observation => 'false',
    :colonist_doctor => 'true',
    :colonist_know_swim => 'true',
    :colonist_swim_school => 'ningunaLos tiburones divertidos',
    :colonist_swim_leave_reasons => 'no seQuedaba lejos de casa',
    :how_know_us => 'Me contó una amiga',
    :parents_relation => 'Casados',
    :father_name => 'Michael Lujambio',
    :father_age => '46',
    :father_lives => 'true',
    :father_visit => 'true',
    :father_email => 'mlujan@mail.com',
    :father_profession => 'camionero',
    :father_work_phone => '11 17458622',
    :mother_name => 'María Eva Duarte',
    :mother_age => '47',
    :mother_lives => 'true',
    :mother_visit => 'true',
    :mother_email => 'm_duart@correo.com',
    :mother_profession => 'Actriz',
    :mother_work_phone => '11 744556328',
    :who_register => 'Madre',
    :i_attest => true,
    :group_id => '4'
  },
  { :colonist_name => 'Brown Eva',
    :colonist_age => '5',
    :colonist_birtday => '9/03/2010',
    :colonist_gender => '2',
    :colonist_dni => '40875325',
    :colonist_address => 'Luis María Campos 47413',
    :colonist_telephone => '123123123',
    :colonist_email => '4pepe@yahoo.com',
    :colonist_school_name => 'Colegio Superior San Martín',
    :colonist_grade => '5',
    :colonist_school_address => 'Lope De Vega 422',
    :colonist_school_phone => '1144215756',
    :colonist_medical_insurance => 'Swiss Medical Group',
    :colonist_trauma => 'no',
    :colonist_surgery => 'no',
    :colonist_illness_asthma => 'false',
    :colonist_illness_allergy => 'no',
    :colonist_illness_heart_failure => 'false',
    :colonist_illness_diabetes => 'true',
    :colonist_illness_other => 'no',
    :colonist_medical_observation => 'false',
    :colonist_doctor => 'true',
    :colonist_know_swim => 'true',
    :colonist_swim_school => 'ninguna',
    :colonist_swim_leave_reasons => 'no se',
    :how_know_us => 'Me llegó un correo electrónico y me interesó la idea',
    :parents_relation => 'Casados',
    :father_name => 'James Brown',
    :father_age => '40',
    :father_lives => 'true',
    :father_visit => 'true',
    :father_email => 'jaimebro@mail.com',
    :father_profession => 'escritor',
    :father_work_phone => '11 12335532',
    :mother_name => 'María Marta Serralima',
    :mother_age => '37',
    :mother_lives => 'true',
    :mother_visit => 'true',
    :mother_email => 'm_martas@correo.com',
    :mother_profession => 'cantante',
    :mother_work_phone => '11 4755628',
    :who_register => 'Madre',
    :i_attest => true,
    :group_id => '2'
  },
  { :colonist_name => 'Mabel Marchesini',
    :colonist_age => '9',
    :colonist_birtday => '9/03/2006',
    :colonist_gender => '2',
    :colonist_dni => '37845235',
    :colonist_address => 'Balboa 5313',
    :colonist_telephone => '123123123',
    :colonist_email => '5pepe@yahoo.com',
    :colonist_school_name => 'Instituto Planc',
    :colonist_grade => '5',
    :colonist_school_address => 'Aragón 1422',
    :colonist_school_phone => '1144215756',
    :colonist_medical_insurance => 'no',
    :colonist_trauma => 'no',
    :colonist_surgery => 'no',
    :colonist_illness_asthma => 'false',
    :colonist_illness_allergy => 'no',
    :colonist_illness_heart_failure => 'false',
    :colonist_illness_diabetes => 'true',
    :colonist_illness_other => 'no',
    :colonist_medical_observation => 'false',
    :colonist_doctor => 'true',
    :colonist_know_swim => 'true',
    :colonist_swim_school => 'ninguna',
    :colonist_swim_leave_reasons => 'no se',
    :how_know_us => 'buscando en google',
    :parents_relation => 'Casados',
    :father_name => 'Roberto Marchesini',
    :father_age => '45',
    :father_lives => 'true',
    :father_visit => 'true',
    :father_email => '5robertimarche@mail.com',
    :father_profession => 'taxista',
    :father_work_phone => '11 1541239',
    :mother_name => 'Lucía Morresi',
    :mother_age => '39',
    :mother_lives => 'true',
    :mother_visit => 'true',
    :mother_email => '5lilimorre@correo.com',
    :mother_profession => 'higiene ambiental',
    :mother_work_phone => '11 47566238',
    :who_register => 'Madre',
    :i_attest => true,
    :group_id => ''
  }
]

colonists.each do |colonist|
  Registration.create!(colonist)
end


# { :colonist_name => '',
# :colonist_age => '',
#    :colonist_birtday => '',
# :colonist_gender => '',
# :colonist_dni => '',
#  :colonist_address => '',
#  :colonist_telephone => '',
#  :colonist_email => '',
#  :colonist_school_name => '',
# :colonist_grade => '',
#  :colonist_school_address => '',
#  :colonist_school_phone => '',
#  :colonist_medical_insurance => '',
#  :colonist_trauma => '',
#  :colonist_surgery => '',
# :colonist_illness_asthma => '',
#  :colonist_illness_allergy => '',
# :colonist_illness_heart_failure => '',
# :colonist_illness_diabetes => '',
#  :colonist_illness_other => '',
# :colonist_medical_observation => '',
# :colonist_doctor => '',
# :colonist_know_swim => 'true :colonist_swim_school => 'ninguna',
#  :colonist_swim_leave_reasons => 'no se',
#  :how_know_us => '',
#  :parents_relation => '',
#  :father_name => '',
# :father_age => '',
# :father_lives => '',
# :father_visit => '',
#  :father_email => '',
#  :father_profession => '',
#  :father_work_phone => '',
#  :mother_name => '',
# :mother_age => '',
# :mother_lives => '',
# :mother_visit => '',
#  :mother_email => '',
#  :mother_profession => '',
#  :mother_work_phone => '',
#  :who_register => '',
# :i_attest => true
# }
