# language: es
Característica: Inscripción a colonia
  Como visitante del sitio y “Tutor”
  Quiero poder inscribir a mi hijo/tutelado en la colonia
  Para que tenga un lugar en la colonia de vacaciones

Antecedentes:
  Dado que estoy en la página inscripciones de la web de la colonia buena onda 

#Camino feliz.
Escenario: Inscripción con datos correctos.
  Y que completo los datos del formulario de inscripción
  Cuando presiono el botón "Inscribir"
  Entonces veo el mensaje de bienvenida a la colonia


Esquema del escenario: datos correctos
    Y completo los datos de mi tutelado y míos con "<nombre_colono>", "<edad_colono>", "<fecha_nac_colono>", "<sexo_colono>", "<dni_colono>", "<domicilio_colono>", "<telefono_colono>", "<email_colono>", "<colegio>", "<grado>", "<direccion_colegio>", "<telefono_colegio>", "<obra_social_colono>", "<traumatismo_colono>", "<cirujias_colono>", "<enfermedades_colono_asma>", "<enfermedades_colono_alergia>", "<enfermedades_colono_ins_card>", "<enfermedades_colono_diabetes>", "<enfermedades_colono_otra>", "<tratamiento_colono>", "<medico_colono_informado>", "<sabe_nadar_colono>", "<a_que_escuela_natacion>", "<por_que_abandono_colono>", "<como_conocio_buena_onda>", "<estado_civil_padres>", "<nombre_padre>", "<edad_padre>", "<vive_padre>", "<ve_padre_habitualmente>", "<email_padre>", "<profesion_padre>", "<telefono_laboral_padre>", "<nombre_madre>", "<edad_madre>", "<vive_madre>", "<ve_madre_habitualmente>", "<mail_madre>", "<profesion_madre>", "<telefono_laboral_madre>", "<quien_registra>", "<doy_fe_check>"
    Cuando presiono el botón "Inscribir"
    Entonces veo el mensaje de bienvenida a la colonia

   Ejemplos: datos correctos
     |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre   |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |

# Casos Extremos.
Esquema del escenario: datos incorrectos
   Y completo los datos de mi tutelado y míos con "<nombre_colono>", "<edad_colono>", "<fecha_nac_colono>", "<sexo_colono>", "<dni_colono>", "<domicilio_colono>", "<telefono_colono>", "<email_colono>", "<colegio>", "<grado>", "<direccion_colegio>", "<telefono_colegio>", "<obra_social_colono>", "<traumatismo_colono>", "<cirujias_colono>", "<enfermedades_colono_asma>", "<enfermedades_colono_alergia>", "<enfermedades_colono_ins_card>", "<enfermedades_colono_diabetes>", "<enfermedades_colono_otra>", "<tratamiento_colono>", "<medico_colono_informado>", "<sabe_nadar_colono>", "<a_que_escuela_natacion>", "<por_que_abandono_colono>", "<como_conocio_buena_onda>", "<estado_civil_padres>", "<nombre_padre>", "<edad_padre>", "<vive_padre>", "<ve_padre_habitualmente>", "<email_padre>", "<profesion_padre>", "<telefono_laboral_padre>", "<nombre_madre>", "<edad_madre>", "<vive_madre>", "<ve_madre_habitualmente>", "<mail_madre>", "<profesion_madre>", "<telefono_laboral_madre>", "<quien_registra>", "<doy_fe_check>"
   Cuando presiono el botón "Inscribir"
   Entonces veo el mensaje "error"

   Ejemplos: faltan datos obligatorios
     |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre   |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
     |                  | 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez|           |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |                |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |           |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |          | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  |                      |44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|               |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |                    | Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com|                |3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|     |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |                           |11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|               |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |                  |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |                 |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |                      |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |                       |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |                   |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |              |35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|          |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |          |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |                      |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |                    |arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|                  |11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|                      |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |            |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |          |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |          |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |                      |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |                    |arquitecta     |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|               |11 24685391           |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |                      |Madre          |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |               |SI        |
     |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |          |

  Ejemplos: datos incorrectos mail incorrecto (sin arroba)
    |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre   |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
    |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               | NO                   |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama1mail.com|arquitecta     |11 24685391           |Madre          |SI          |
    |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               | NO                   |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa2mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |
    |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12hotmail.com | Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               | NO                   |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |

  Ejemplos: Nombres con Numeros.
    |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre   |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
    |Juan J41into Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |
    |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Pa6ricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |
    |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Al2a Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |

  Ejemplos: datos incorrectos #letras en dni colono             
    |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre   |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
    |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |a40t2456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |
    |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |29.123123 | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |
  

  Ejemplos: datos incorrectos #letras en telefono colegio   
    |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre   |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
    |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11 4aaa87d63    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |

  Ejemplos: datos incorrectos #nuimeros en obra social colono
    |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre   |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
    |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |OSDE 2000         |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |


   
# TO-DO: esperando los ejemplos de Simon.
 Esquema del escenario: datos formato incorrectos
   Y completo los datos de mi tutelado y míos con "<nombre_colono>", "<edad_colono>", "<fecha_nac_colono>", "<sexo_colono>", "<dni_colono>", "<domicilio_colono>", "<telefono_colono>", "<email_colono>", "<colegio>", "<grado>", "<direccion_colegio>", "<telefono_colegio>", "<obra_social_colono>", "<traumatismo_colono>", "<cirujias_colono>", "<enfermedades_colono_asma>", "<enfermedades_colono_alergia>", "<enfermedades_colono_ins_card>", "<enfermedades_colono_diabetes>", "<enfermedades_colono_otra>", "<tratamiento_colono>", "<medico_colono_informado>", "<sabe_nadar_colono>", "<a_que_escuela_natacion>", "<por_que_abandono_colono>", "<como_conocio_buena_onda>", "<estado_civil_padres>", "<nombre_padre>", "<edad_padre>", "<vive_padre>", "<ve_padre_habitualmente>", "<email_padre>", "<profesion_padre>", "<telefono_laboral_padre>", "<nombre_madre>", "<edad_madre>", "<vive_madre>", "<ve_madre_habitualmente>", "<mail_madre>", "<profesion_madre>", "<telefono_laboral_madre>", "<quien_registra>", "<doy_fe_check>"
   Cuando presiono el botón "Inscribir"
   Entonces veo el mensaje "error"

Ejemplos: datos incorrectos nombre colono con números
    |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|concurrio_a_escuela_natacion_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre   |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
    |Juan Jac2nto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11 425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |NO                     |SI               |NO                                 |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |true        |

## Aca empeza a poner tus ejemplos Simon ##
 Ejemplos: datos incorrectos números en nombre colono
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Jua3 Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos nombre colono vacío
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |                  | 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos letras en edad colono
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| s         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos edad colono vacío
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez|           |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos fecha_nac_colono vacío
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |                |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos sexo_colono vacío
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |           |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos dni colono con letras
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54s12456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos dni_colono vacío
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |          | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos domicilio colono solo números
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | 135435468542213330550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos domicilio colono vacío
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  |                      |44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos telefono_colono vacío
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|               |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos telefono_colono con letras
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444s44444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos email_colono sin arroba
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12ahotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos obra social colono solo números
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |2152              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos nombre padre con números
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patr4cio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos edad_padre con letras
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|3s        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos email_padre sin arroba
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papasmail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos profesion_padre solo números
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|4255858123233223l|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos telefono padre con letras
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74d69247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos nombre madre con números
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Rogg3o |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos mail madre sin arroba
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mamaamail.com|arquitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos profesion madre con números
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|a5quitecta     |11 24685391           |Madre          |SI          | 

Ejemplos: datos incorrectos telefono_madre con letras
 |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre  |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
 |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |54012456  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963     |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24s85391           |Madre          |SI          | 




#Ejemplos: longitudes de datos incorrectos.
#Ejemplos: datos incorrectos #nuimeros en obra social colono
#  |nombre_colono     |edad_colono|fecha_nac_colono|sexo_colono|dni_colono| domicilio_colono     |telefono_colono|email_colono        | colegio        |grado|direccion_colegio          |telefono_colegio|obra_social_colono|traumatismo_colono|cirujias_colono|enfermedades_colono_asma|enfermedades_colono_alergia|enfermedades_colono_ins_card|enfermedades_colono_diabetes|enfermedades_colono_otra|tratamiento_colono|medico_colono_informado|sabe_nadar_colono|a_que_escuela_natacion|por_que_abandono_colono|como_conocio_buena_onda|estado_civil_padres|nombre_padre  |edad_padre|vive_padre|ve_padre_habitualmente|email_padre         |profesion_padre   |telefono_laboral_padre|nombre_madre|edad_madre|vive_madre|ve_madre_habitualmente|mail_madre          |profesion_madre|telefono_laboral_madre|quien_registra |doy_fe_check|
#DNI menor y mayor.
#  |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |29999999  | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |
#  |Juan Jacinto Perez| 5         |13/08/2008      |Varon      |100000000 | Av. Cabildo Nro 10550|44444444444    |colono12@hotmail.com| Sagrado corazón|3    |Luis María Campos Nro. 5550|11425587963    |osde              |NO                |NO             |NO                      |NO                         |NO                          |NO                          |NO                      |NO                |SI                     |SI               |NO                    |ninguna                |página de internet     |Casado             |Patricio Perez|35        |SI        |SI                    |correo_papa@mail.com|arquero de  futbol|11 74569247           |Alba Roggio |33        |SI        |SI                    |correo_mama@mail.com|arquitecta     |11 24685391           |Madre          |SI          |

#Escenario: agrega al grupo correcto.
    # Dado que inscribo un nene de 4, 
    # Y que existe un grupo de 4 a 5.
    # Entonces asocia el inscripto al grupo de 4.

#Escenario: No hay cupo.

#Escenario: DNI repetido.??

#Escenario: Completar CAPTCHA.
#  Y que completo los datos del formulario de inscripción
#  Y completo el CAPTCHA
#  Cuando presiono el botón "Inscribir"
#  Entonces veo el mensaje de bienvenida a la colonia

@wip @to-do
Escenario: Inscripción con datos correctos + email confirmación
